// Generated by CoffeeScript 1.6.2
var Listener, WrapperHClient, listener, password, user, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

WrapperHClient = require("./wrapper_hclient");

Listener = (function(_super) {
  __extends(Listener, _super);

  function Listener() {
    _ref = Listener.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Listener;

})(WrapperHClient);

listener = new Listener({
  hOptions: {
    endpoints: [
      {
        "http://test.apila.fr:8080": "http://test.apila.fr:8080"
      }
    ]
  }
});

user = password = "urn:localhost:listen";

listener.connect(user, password);

listener.onOpen(function() {
  return console.log("open");
});
